server:
  context-path: /web
  port: 8888

grpc:
  client:
    local-grpc-server:
      host: 127.0.0.1
      port: 9898
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

